//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALevelRport
    {
        public int ALReportId { get; set; }
        public string Name { get; set; }
        public string County { get; set; }
        public string WaterBody { get; set; }
        public string Level { get; set; }
    }
}
