//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnglersCampEntities : DbContext
    {
        public AnglersCampEntities()
            : base("name=AnglersCampEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALevelRport> ALevelRports { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<WaterLevel> WaterLevels { get; set; }
    }
}
