//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Clubs = new HashSet<Club>();
            this.Reports = new HashSet<Report>();
        }
    
        public int MemberId { get; set; }
        public string MemberName { get; set; }
        public string MemberEmail { get; set; }
        public string MemberPassword { get; set; }
        public string MemberPicture { get; set; }
        public string MemberClub { get; set; }
        public string MemberType { get; set; }
    
        public virtual ICollection<Club> Clubs { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}
