//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportId { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string Location { get; set; }
        public string Tactics { get; set; }
        public string Species { get; set; }
        public string Picture { get; set; }
        public string Visibility { get; set; }
        public int MemberId { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
